repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.1.0
  hooks:
  - id: trailing-whitespace
  - id: check-docstring-first
  - id: debug-statements
  - id: name-tests-test
  - id: requirements-txt-fixer
- repo: https://github.com/pre-commit/mirrors-autopep8
  rev: v1.4.3
  hooks:
  - id: autopep8
    exclude: ^forge_sdk/protos/
- repo: https://github.com/pre-commit/pre-commit
  rev: v1.13.0
  hooks:
  - id: validate_manifest
    exclude: ^forge_sdk/protos/
- repo: https://github.com/asottile/reorder_python_imports
  rev: v1.3.4
  hooks:
  - id: reorder-python-imports
    language_version: python3.6
    exclude: ^forge_sdk/protos/
