[app]
name = "Event-Chain"
version = "0.1.0"
sock_tcp = "tcp://127.0.0.1:27219"
path = "~/.forge/event_chain"
host="10.1.10.177"
port=5000
did_address='http://localhost:4000'
# sock_grpc = "tcp://127.0.0.1:37210"
